sudo: required
services:
  - docker

before_install:
 - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
 - docker build -t cbastias/frontend:v3 -f Dockerfile.dev .

script:
 - docker run -e CI=true  cbastias/frontend:v3 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: frontend
  env: frontend-env
  bucket_name: elasticbeanstalk-us-east-1-491023448192
  bucket_path: frontend
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
